version: '3.8'

services:
  ocr-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: baidu-ocr-app:latest
    container_name: baidu-ocr-app
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - BAIDU_OCR_API_KEY=${BAIDU_OCR_API_KEY:-Io2AFs0q1pPmzlxxYn44dMmR}
      - BAIDU_OCR_SECRET_KEY=${BAIDU_OCR_SECRET_KEY:-09cMxoWTA7UG7ekNIjs8AYJIJWvuXRUW}
    volumes:
      - ./app/data:/app/app/data
      - ./app/logs:/app/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - ocr-network

networks:
  ocr-network:
    driver: bridge
